### PR TITLE
[Cargo.toml] update rand to 0.7 (breaking change)

### PR DESCRIPTION
**Pull request by niklasad1**
Needed by https://github.com/paritytech/parity-ethereum/pull/11022

### CODE REVIEW

**Review by ordian — APPROVED** [review]

**Comment by dvdplm** [comment]
@niklasad1 @ordian is this a good time to update our fork with the upstream changes?

**Comment by ordian** [comment]
@dvdplm our fork has diverged a bit https://github.com/rust-bitcoin/rust-secp256k1/compare/master...paritytech:master, so it could be quite involved, but we need to do this for sure.

**Comment by dvdplm** [comment]
> so it could be quite involved, but we need to do this for sure.

Has a stab at this. It's a bit fiddly but not too bad tbh. I'll hold off until @grbIzl is done with his work on `ethkey`.

**Comment by niklasad1** [comment]
@dvdplm @ordian can we merge this?

**Comment by dvdplm** [comment]
@niklasad1 there was some talk over on [the dalek lib to skip `0.7` altogether](https://github.com/dalek-cryptography/ed25519-dalek/issues/89) (apparently a very minor change not worthy of a semver-minor bump). I honestly don't know why not upgrade (or conversely what the reasons are to upgrade). 

Can you explain why we want to upgrade? Maybe you did already but I have goldfish memory... ;)

**Comment by dvdplm** [comment]
> Can you explain why we want to upgrade? Maybe you did already but I have goldfish memory... ;)

Nvm, ignore me. We've already made the decision to go with `0.7` when we merged the PR in `parity-common`.

**Review by dvdplm — APPROVED** [review]

**Comment by niklasad1** [comment]
Yes, after https://github.com/paritytech/parity-ethereum/pull/11139 lands it could make sense to merge this and use `rand 0.7`. However, I'm not sure if use this crate somewhere else than in `parity-ethereum`.

**Comment by dvdplm** [comment]
> I'm not sure if use this crate somewhere else than in `parity-ethereum`.

`rust-libp2p` uses upstream (https://github.com/rust-bitcoin/rust-secp256k1/) and substrate uses https://github.com/sorpaas/libsecp256k1-rs so I think `parity-ethereum` is the only one.

**Comment by dvdplm** [comment]
Looks like CI needs a kick in the butt here. :/

**Comment by niklasad1** [comment]
I changed the `trait bounds` in the tests after you approved it, ok to merge?

**Pull request merged**
